apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      deploymentInformation: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
  template:
    metadata:
      labels:
        deploymentInformation: DEPLOYMENT_INFORMATION # This is a placeholder that will get replaced
    spec:
      nodeSelector:
        kubernetes.io/hostname: NODE_SELECTOR # This is a placeholder that will get replaced