apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    deploymentInformation: hello-world-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5678
  type: LoadBalancer
